services:

  frontend:
    build: frontend
    ports:
      - "20080:80"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    depends_on:
      - mysql
    networks:
      - yii2-network
    environment:
      - YII_DEBUG=true
      - YII_ENV=dev

  backend:
    build: backend
    ports:
      - "22080:80"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    depends_on:
      - mysql
    networks:
      - yii2-network
    environment:
      - YII_DEBUG=true
      - YII_ENV=dev

  mysql:
    image: mysql:8.0
    container_name: delevery_mysql
    restart: always
    ports:
      - "33070:3306"
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - yii2-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: delevery_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: verysecret
      UPLOAD_LIMIT: 100M
    depends_on:
      - mysql
    networks:
      - yii2-network

volumes:
  mysql_data:
    driver: local

networks:
  yii2-network:
    driver: bridge